server: "https://qn.nya-wsl.cn" # 资源文件所在服务器，如果下面的Url部分开头有“/”，末尾不要添加“/”
version: 2.0.0 # 客户端版本
language: auto # 客户端语言，auto=自动识别,可手动指定语言
default_lang: en_us # 自动识别失败的默认语言
check_server_list: online # online: 从服务器获取列表 | offline: 读取本地文件
auto_update: True # 如果为True，将自动更新；如果为False，只会检测版本而不会自动更新

Url:
  csvUrl: "/files/ServerList.csv" # 服务器上的列表文件所在路径
  conUrl: "/files/n2n_config.html" # 服务器上的版本文件所在路径
  zipUrl: "/files/n2n_update_win.zip" # 服务器上的更新包所在路径
  updateUrl: "/files/update.exe" # 获取更新模块的路径
  historyUrl: "/files/history.json" # n2n连接的默认历史记录，仅本地不存在时下载

Path:
  csvRes: "./ServerList.csv" # 服务器列表文件本地保存路径
  csvFile: "ServerList.csv"
  local_list: "./LocalServerList.csv"
  updateRes: update.exe # 更新模块保存路径
  updateLog: update.log # win版特有的更新模块日志保存路径
  historyRes: history.json # 历史记录保存路径